root: true

env:
  es2020: true

extends:
  - '@cordisjs/eslint-config'

parser: '@typescript-eslint/parser'

rules:
  operator-linebreak:
    - error
    - after
    - overrides:
        '?': before
        ':': before
  lines-between-class-members:
    - error
    - enforce:
        - blankLine: never
          prev: field
          next: field
        - blankLine: always
          prev: '*'
          next: '*'
  indent: off
